### ISSUE TITLE
"where()" and "pagination" together not working ?

### ISSUE THREAD

**Issue by aymann** [nicolaslopezj/searchable#106]
when I try to use where() and patination the query not working and give me error:

I try this;
  $products= Product::where('status', "publish")
            ->search("sdf")
            ->paginate(20);

and the laravel give me this error:
 Invalid parameter number (SQL: select count(*) as aggregate from (select `products`.*, max((case when LOWER(`products`.`id`) LIKE publish then 150 else 0 end) + (case when LOWER(`products`.`id`) LIKE publish then 50 else 0 end) + (case when LOWER(`products`.`id`) LIKE ? then 10 else 0 end) + (case when LOWER(`products`.`keyword`) LIKE ? then 150 else 0 end) + (case when LOWER(`products`.`keyword`) LIKE ? then 50 else 0 end) + (case when LOWER(`products`.`keyword`) LIKE ? then 10 else 0 end)) as relevance from `products` left join `product_translations` on `products`.`id` = `product_translations`.`product_id` where `status` = ? and `products`.`deleted_at` is null group by `products`.`id` having relevance > 5.00 order by `relevance` desc) as `products` where `status` = ? and `products`.`deleted_at` is null)

**Comment by leyluj** [comment]
I'm getting the same issue? What happened?
