### ISSUE TITLE
Vague use of column value

### ISSUE THREAD

**Issue by doncadavona** [nicolaslopezj/searchable#122]
In the docs, the column value set in the `$searchable` is **vague** or **unclear**.
What exactly is the use of the column values  such as here, `users.first_name` is set to 10, `users.bio` is 2 users.email is 5 and so fort.

```
/**
 * Searchable rules.
 *
 * @var array
 */
protected $searchable = [
    'columns' => [
        'users.first_name' => 10, // What does 10, 2, 5 and so fort mean?
        'users.last_name' => 10,
        'users.bio' => 2,
        'users.email' => 5,
        'posts.title' => 2,
        'posts.body' => 1,
    ],
    'joins' => [
        'posts' => ['users.id','posts.user_id'],
    ],
];
```

Thanks!

**Comment by nicolaslopezj** [comment]
The priority. Bigger is more important.

Please make a pr to change the docs so everyone can understand

**Comment by doncadavona** [comment]
So I suppose that the maximum column value is not limited because it won't matter. But it should be better that the maximum column value is the total number of columns for clarity. Like in the example, there are 6. So 10 is practically equal to 6. Or, wouldn't it be best to base the priority based on the ordering of the columns? For example:,

```
/**
* Searchable rules.
*
* @var array
*/
protected $searchable = [
    'columns' => [
        'users.first_name', // highest priority
        'users.last_name',
        'users.bio',
        'users.email',
        'posts.title',
        'posts.body' // lowest priority
    ],
    'joins' => [
        'posts' => ['users.id','posts.user_id'],
    ],
];
```

But equal priorities won't look good on that. To edit this.

**Comment by nicolaslopezj** [comment]
No, you can put any number you want. A very important attribute can have 50 and a almost no importat attribute can have 1

**Comment by doncadavona** [comment]
If two attributes have priorities of 2 and 1, will there be difference if they instead have 50 and 1?

**Comment by nicolaslopezj** [comment]
Yes, there will be difference. If the row has the attribute, searchable will add 50 or 1 points of relevance. Then, it will order by relevance points
