### ISSUE TITLE
Column not found: 1054 Unknown column 'font.id' in 'group statement' 

### ISSUE THREAD

**Issue by scottyloots** [nicolaslopezj/searchable#123]
My naming convention for my primary key is not simply 'id'.  Is there a way to pass a string to update this?

**Comment by gfd6th** [comment]
I got the same issue when I used mariadb, but it works fine if I change to mysql

**Comment by vdellangela** [comment]
In your model, you can declare the primary field:

protected $primaryKey = 'column_name';
