### ISSUE TITLE
how to search if i have more than one word in one database field

### ISSUE THREAD

**Issue by constantinosergiou** [nicolaslopezj/searchable#150]
e.g company.name => testing test2 
Company::search($query, null, false)->with(['City', 'Town', 'GlobalCategory', 'CompanyCertification']);

when i search testing it will show me the result correct if i search test2 it doesnt fetch ... when i do   testing test2 it fetch ...  how can i fix it ?

**Comment by dwin-dev** [comment]
hello  @constantinosergiou  try using this 

Company::search("testing test2", null, true, true)->with(['City', 'Town', 'GlobalCategory', 'CompanyCertification']);

**Comment by constantinosergiou** [comment]
thanks
