### ISSUE TITLE
Possible to search against a GROUP_CONCAT ?

### ISSUE THREAD

**Issue by mefenlon** [nicolaslopezj/searchable#180]
Here are my Illustration model

    protected $searchable = [
        'columns' => [
            'caption' => 15,
            'articles.title' => 9,
            'indextags.text' => 10,
        ],
        'joins' => [
            'illustration_indextag' => ['illustrations.id','illustration_indextag.illustration_id'], //pivot table
            'indextags' => ['illustration_indextag.indextag_id','indextags.id'],
            'articles' => ['articles.id','illustrations.article_id'],
        ],
    ];
    //Article relationship
    public function article()
    {
        return $this->belongsTo('App\Article');
    }
    //Indextag relationship
    public function indextags()
    {
        return $this->belongsToMany('App\Indextag', 'illustration_indextag', 'illustration_id', 'indextag_id');
    }

What I would really like to do is search against a concatenated group of all indextags. Something like
GROUP_CONCAT(indextags.text) as ALLTAGS
Resulting in a query 

SELECT 
        `illustrations`.*,
            MAX((CASE
                WHEN LOWER(`caption`) LIKE 'meyerbeer' THEN 75
                ELSE 0
            END) + (CASE
                WHEN LOWER(`caption`) LIKE 'caricature' THEN 75
                ELSE 0
            END) + (CASE
                WHEN LOWER(`caption`) LIKE 'meyerbeer%' THEN 25
                ELSE 0
            END) + (CASE
                WHEN LOWER(`caption`) LIKE 'caricature%' THEN 25
                ELSE 0
            END) + (CASE
                WHEN LOWER(`caption`) LIKE '%meyerbeer%' THEN 5
                ELSE 0
            END) + (CASE
                WHEN LOWER(`caption`) LIKE '%caricature%' THEN 5
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE 'meyerbeer' THEN 30
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE 'caricature' THEN 30
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE 'meyerbeer%' THEN 10
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE 'caricature%' THEN 10
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE '%meyerbeer%' THEN 2
                ELSE 0
            END) + (CASE
                WHEN LOWER(`articles`.`title`) LIKE '%caricature%' THEN 2
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE 'meyerbeer' THEN 150
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE 'caricature' THEN 150
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE 'meyerbeer%' THEN 50
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE 'caricature%' THEN 50
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE '%meyerbeer%' THEN 10
                ELSE 0
            END) + (CASE
                WHEN LOWER(`ALLTAGS`) LIKE '%caricature%' THEN 10
                ELSE 0
            END)) AS relevance
    FROM
        `illustrations`
    LEFT JOIN `illustration_indextag` ON `illustrations`.`id` = `illustration_indextag`.`illustration_id`
    LEFT JOIN `indextags` ON `illustration_indextag`.`indextag_id` = `indextags`.`id`
    LEFT JOIN `articles` ON `articles`.`id` = `illustrations`.`article_id`
    LEFT JOIN `illustration_illustrator` ON `illustrations`.`id` = `illustration_illustrator`.`illustration_id`
    LEFT JOIN `names` ON `illustration_illustrator`.`name_id` = `names`.`id`
    GROUP BY `illustrations`.`id` , `names`.`text` , `articles`.`title` , `articles`.`date_iso` , `indextags`.`text`
    HAVING relevance >= 4.75
    ORDER BY `relevance` DESC) AS `illustrations`

I am guessing I would need to supply a raw query before I run my search(), but I really have no idea where to start.

Thank you for your help with this.

**Comment by ajcastro** [comment]
@mefenlon maybe that is possible here.. 
https://github.com/ajcastro/searchable
