### ISSUE TITLE
array_get() undefined in >= Laravel 5.7

### ISSUE THREAD

**Issue by jsdecena** [nicolaslopezj/searchable#191]
array_get() is now replaced by Arr::get() static method instead of helper.
```
{#1539
  +"errors": array:1 [
    0 => {#1542
      +"code": 500
      +"detail": "Call to undefined function Nicolaslopezj\Searchable\array_get()"
    }
  ]
}

```

Made a PR for this https://github.com/nicolaslopezj/searchable/pull/192 @nicolaslopezj

**Comment by Ezequielcc1** [comment]
it is true , Thanks  do you can commit it  ?

**Comment by jsdmultisys** [comment]
@Ezequielcc1 The comment above has the PR link

**Comment by jsdecena** [comment]
@Ezequielcc1 The issue above has the PR link

**Comment by jsdecena** [comment]
closing this bec the PR has been merged
