### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by v1r0x** [nicolaslopezj/searchable#197]
Laravel 6 release is only [one week away](https://laravel-news.com/is-laravel-6-0-out-yet)! :rocket: 
I can not update to current Laravel 6 dev release, because it requires `illuminate/database` in version 6.

Would be great to have this package available in Laravel 6 :)

**Comment by alvinbakker** [comment]
Yes please

**Comment by radd2004** [comment]
Looks like we have a pull requestion for laravel 6 support: https://github.com/nicolaslopezj/searchable/pull/198

@nicolaslopezj @jarnovanleeuwen  can we pretty please get that merged in?

**Comment by jarnovanleeuwen** [comment]
I'd be happy to, but I am not the maintainer of this package..

**Comment by kylekatarnls** [comment]
Hi @nicolaslopezj thanks for the release with Laravel 6!

It's not yet available on packagist:
https://packagist.org/packages/nicolaslopezj/searchable

Is the new packagist hook system well set?

**Comment by nicolaslopezj** [comment]
It's published! Version 1.12.0
