### ISSUE TITLE
Any news on Laravel 7.0?

### ISSUE THREAD

**Issue by caiokawasaki** [nicolaslopezj/searchable#209]
Release will be on 3rd march

**Comment by LewisLarsen** [comment]
Hopefully this will be supported, can't do without it. :)

**Comment by caiokawasaki** [comment]
@nicolaslopezj please review: #210

**Comment by dellow** [comment]
@nicolaslopezj Please can we get this merged?

**Comment by kevindesousa** [comment]
Please ?

**Comment by dellow** [comment]
@kevindesousa I've forked this (https://github.com/dellow/searchable) readme describes how to use the forked version.

**Comment by seewhy17** [comment]
> @kevindesousa I've forked this (https://github.com/dellow/searchable) readme describes how to use the forked version.

Hi, can you work me through how to pull in your fork((https://github.com/dellow/searchable) into a Laravel 7 (stable, not dev) project.
🙏

**Comment by dellow** [comment]
@seewhy17 Have you seen the instructions in the readme? Will work just fine.

**Comment by seewhy17** [comment]
> @seewhy17 Have you seen the instructions in the readme? Will work just fine.
> 
> There was a typo in the readme which referenced the wrong repo but that is fixed now.

Thanks @dellow I was able to  pull it into my Laravel 7.x.x project

**Comment by mbvb1223** [comment]
The owner has just merged this PR: https://github.com/nicolaslopezj/searchable/pull/214
I think it can resolve your problem

**Comment by dellow** [comment]
@seewhy17 I'll be removing the forked repo very soon as the latest release of this repo now supports Laravel 7
