### ISSUE TITLE
How to achieve and query

### ISSUE THREAD

**Issue by XinJiangQingMang** [nicolaslopezj/searchable#217]
thanks!

for example i have this table

------------------------------
id|name | age
-|-|-
 1|jhon smith   |     15
2|melodic        |    13
3|jhon xxx         |   11

how to query such as 'jhon* 15'  
```
 \App\Models\Tests::search('jhon* 15')->paginate(20)->toArray();
```

result:
id|name | age
-|-|-
1|jhon smith| 15

The results satisfy two conditions at the same time

**Comment by isneezy** [comment]
Please post your model definition
