### ISSUE TITLE
count() method broken 

### ISSUE THREAD

**Issue by jwohlfert23** [nicolaslopezj/searchable#23]
Getting the following error when trying to use the count() method on the query builder
```
Column not found: 1054 Unknown column 'relevance' in 'order clause' (SQL: select count(*) as aggregate from `categories` group by `id` having relevance > 3.75 order by `relevance` desc)
```

**Comment by jwohlfert23** [comment]
It's because of the "groupBy" statement. Had to use a subquery to solve this:
```
$sub = with(clone $this->query);
$total = DB::table(DB::raw("({$sub->toSql()}) as sub"))
      ->mergeBindings($sub->getQuery())
      ->count();
```

Don't know if there is any way to solve this within a scope method

**Comment by nicolaslopezj** [comment]
Its the same problem of #21.
In Laravel 4 the count was made differently to queries that use group by, I don't know how that works now.

**Comment by eristoddle** [comment]
I am having similar issues when I am not even using count. I am doing a union across subqueries that all have joins. Somehow Laravel throws this same error with a select count(*) in the query I never put there in the first place.
