### ISSUE TITLE
Threshold 0 is ignored

### ISSUE THREAD

**Issue by mk-relax** [nicolaslopezj/searchable#29]
The documentation states that passing a `threshold` parameter to `search()` will overrule the default threshold value, the example being `->search($query, 0)` to return all records. However, by passing `0`, the default threshold will still be applied because `0` is falsey, just like `null`. The line of code to be changed would probably be:

    $threshold ?: ($relevance_count / 4)

**Comment by nicolaslopezj** [comment]
@mk-relax you can make a pull request if you want!
