### ISSUE TITLE
sql error on attribute name desc

### ISSUE THREAD

**Issue by siegessa** [nicolaslopezj/searchable#59]
if i use table attribute name 'desc', it gives error below, if I change it to other name it works.

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'desc) LIKE ? then 150 else 0 end) + (case when LOWER(desc) LIKE ? then 50 else 0' at line 1 (SQL: select * from

**Comment by jarektkaczyk** [comment]
`desc` is reserved keyword and column names are not wrapped correctly, so the error happens. You can use [this](https://github.com/jarektkaczyk/eloquence/wiki/Builder-searchable-and-more#searchable) instead, unless there will be a quick fix.

**Comment by JulienTant** [comment]
https://github.com/nicolaslopezj/searchable/pull/60 should fix your issue :)
