### ISSUE TITLE
Search fails when joins are included.

### ISSUE THREAD

**Issue by RJacksonm1** [nicolaslopezj/searchable#75]
I have something funky going on with the "relevance" alias in the query, which is causing a search to not return any results, despite there being valid results to match.

The code I have that is failing is:

```
SELECT DISTINCT `questions`.*,
	 (CASE WHEN LOWER(`title`) LIKE 'commodi' THEN 60 ELSE 0 END) + 
    (CASE WHEN LOWER(`title`) LIKE 'commodi%' THEN 20 ELSE 0 END) + 
    (CASE WHEN LOWER(`title`) LIKE '%commodi%' THEN 4 ELSE 0 END) AS relevance
 FROM `questions`
 LEFT JOIN `commentable_entities` AS `question_commentable_entities` ON `commentable_entity_id_question` = `question_commentable_entities`.`id`
 LEFT JOIN `commentable_entities` AS `answer_commentable_entities` ON `commentable_entity_id_answer` = `answer_commentable_entities`.`id`
 LEFT JOIN `comments` AS `question_comments` ON `question_comments`.`commentable_entity_id` = `question_commentable_entities`.`id`
 LEFT JOIN `comments` AS `answer_comments` ON `answer_comments`.`commentable_entity_id` = `answer_commentable_entities`.`id`
 WHERE `questions`.`deleted_at` IS NULL
 GROUP BY `questions`.`id`
 HAVING relevance > 0
 ORDER BY `relevance` DESC
```

I have one row that has a relevance of 4, and many rows with a relevance of zero, but no results are returned from the query.

If I remove the JOINs from the query, it works fine and returns the rows as expected.

A colleague of mine also figured out a fix for the issue, where instead of `HAVING relevance > 0` we instead just do the select statement again - `having (CASE WHEN ...) > 0)`.

Digging into the code, I found the function `filterQueryWithRelevance` already sets up the HAVING clause with this method that works for all database drivers EXCEPT mysql:

https://github.com/RJacksonm1/searchable/blob/master/src/SearchableTrait.php#L187

I can't find any sort of documentation or rationale as to why this mysql-specific exclusion was included.  This check was initially set up to check if the database driver was PostgreSQL with commit a1956ee23edc8a041667909b7cf8923696d1c3d1, titled `sql injection security`, though that title seems irrelevant to this actual change.

Do you know why this check exists and if its important?  I've removed it in a branch on my fork of this repository to fix the issue for my project, so if there is a problem introduced by my removal I'd like to know. :x

Thanks

**Comment by joostbaptist** [comment]
Hi, a little late, but I just ran into the same issue. I found that running the query with either 1) no GROUP BY clause, or 2) an aggregate function (such as SUM or AVG) over the relevance score, fixes it. I believe in this case a GROUP BY clause is not necessary. Perhaps you could check if this fixes it for you as well.

Aggregate:

    SELECT DISTINCT `questions`.*,
         sum((CASE WHEN LOWER(`title`) LIKE 'commodi' THEN 60 ELSE 0 END) + 
        (CASE WHEN LOWER(`title`) LIKE 'commodi%' THEN 20 ELSE 0 END) + 
        (CASE WHEN LOWER(`title`) LIKE '%commodi%' THEN 4 ELSE 0 END)) AS relevance
     FROM `questions`
     LEFT JOIN `commentable_entities` AS `question_commentable_entities` ON `commentable_entity_id_question` = `question_commentable_entities`.`id`
     LEFT JOIN `commentable_entities` AS `answer_commentable_entities` ON `commentable_entity_id_answer` = `answer_commentable_entities`.`id`
     LEFT JOIN `comments` AS `question_comments` ON `question_comments`.`commentable_entity_id` = `question_commentable_entities`.`id`
     LEFT JOIN `comments` AS `answer_comments` ON `answer_comments`.`commentable_entity_id` = `answer_commentable_entities`.`id`
     WHERE `questions`.`deleted_at` IS NULL
     GROUP BY `questions`.`id`
     HAVING relevance > 0
     ORDER BY `relevance` DESC

No GROUP BY:

    SELECT DISTINCT `questions`.*,
         (CASE WHEN LOWER(`title`) LIKE 'commodi' THEN 60 ELSE 0 END) + 
        (CASE WHEN LOWER(`title`) LIKE 'commodi%' THEN 20 ELSE 0 END) + 
        (CASE WHEN LOWER(`title`) LIKE '%commodi%' THEN 4 ELSE 0 END) AS relevance
     FROM `questions`
     LEFT JOIN `commentable_entities` AS `question_commentable_entities` ON `commentable_entity_id_question` = `question_commentable_entities`.`id`
     LEFT JOIN `commentable_entities` AS `answer_commentable_entities` ON `commentable_entity_id_answer` = `answer_commentable_entities`.`id`
     LEFT JOIN `comments` AS `question_comments` ON `question_comments`.`commentable_entity_id` = `question_commentable_entities`.`id`
     LEFT JOIN `comments` AS `answer_comments` ON `answer_comments`.`commentable_entity_id` = `answer_commentable_entities`.`id`
     WHERE `questions`.`deleted_at` IS NULL
     HAVING relevance > 0
     ORDER BY `relevance` DESC
